language: python
dist: xenial

python:
  - "2.7"

addons:
  artifacts:
    paths: "./dist/"
    debug: true

matrix:
  include:
    - os: osx
      language: sh
      python: "2.7"
      before_install:
        - brew update
        - brew install unix2dos
        - pip install pyinstaller wxpython pyxform
      script:
        - ./make-dist.sh
    - os: windows
      language: sh
      python: "2.x"
      before_install:
        - choco install python2 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - pip install pyinstaller
        - pip install pyxform
      script:
        - ./make-dist.sh

cache: pip